version: '3.7'

services:
  server:
    build: ./back-end
    restart: always
    ports:
      - '3015:3015'
    environment:
      HOST: 'coinlitics.ru'
  client:
    build: ./front-end
    restart: always
    ports:
      - '3010:3010'
