export const HANDLE_COLLAPSE_SIDE_MENU = 'HANDLE_COLLAPSE_SIDE_MENU';
export const HANDLE_SHOW_AUTH_MODAL = 'HANDLE_SHOW_AUTH_MODAL';
export const HANDLE_SHOW_REGISTRATION_MODAL = 'HANDLE_SHOW_REGISTRATION_MODAL';
export const SET_NOTIFICATION_FORM = 'SET_NOTIFICATION_FORM';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_LOADING_SUCCESS = 'GET_LOADING_SUCCESS';
export const GET_LOADING_PENDING = 'GET_LOADING_PENDING';

export const AUTH_PENDING = 'AUTH_PENDING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const REGISTRATION_PENDING = 'REGISTRATION_PENDING';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';

export const GET_AUTHORIZATION_STATUS_PENDING = 'GET_AUTHORIZATION_STATUS_PENDING';
export const GET_AUTHORIZATION_STATUS_SUCCESS = 'GET_AUTHORIZATION_STATUS_SUCCESS';
export const GET_AUTHORIZATION_STATUS_FAILURE = 'GET_AUTHORIZATION_STATUS_FAILURE';

export const GET_GOOGLE_AUTHORIZATION_PENDING = 'GET_GOOGLE_AUTHORIZATION_PENDING';
export const GET_GOOGLE_AUTHORIZATION_SUCCESS = 'GET_GOOGLE_AUTHORIZATION_SUCCESS';
export const GET_GOOGLE_AUTHORIZATION_FAILURE = 'GET_GOOGLE_AUTHORIZATION_FAILURE';
