name: Deploy project

env:
  # SERVER_IP: 185.20.227.11
  SERVER_IP: 146.190.239.103

on:
  push:
    branches:
      - 'master'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-end
    steps:
      - uses: actions/checkout@v2
      - name: Setup key
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.KEY }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
      - name: Deploy
        run: rsync -a --progress --human-readable -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --delete --exclude-from 'exclude-list.txt' . root@${{ env.SERVER_IP }}:/home/deploy/CWA/back-end/
      - name: Restart cwa pm2
        uses: appleboy/ssh-action@master
        with:
          host: '${{ env.SERVER_IP }}'
          username: root
          key: ${{ secrets.KEY }}
          script: |
            pushd /home/deploy/CWA/back-end/
            yarn
            pm2 restart cwa
            popd

  deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front-end
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: CI=false npm run build
      - name: Setup key
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.KEY }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
      - name: Deploy
        run: rsync -a --progress --human-readable -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete build/ root@${{ env.SERVER_IP }}:/home/deploy/CWA/front-end/build/
