name: Check

on:
  pull_request:
    branches:
      - 'master'
jobs:
  lint-backend:
    runs-on: ubuntu-latest
    container:
      image: node:16.13.1-alpine
    defaults:
      run:
        working-directory: ./back-end
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
